[build]
  base = "local_lift_digital"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[secrets_scanning]
  omit_keys = [
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_APP_ID",
    "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
  ]

  [build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache"