[build]
  base = "local_lift_digital"
  command = "npm run build"
  publish = ".next"

[secrets_scanning]
  omit_keys = [
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_APP_ID",
    "NEXT_PUBLIC_GA_MEASUREMENT_ID"
  ]