[build]
  base = "local_lift_digital"
  command = "npm run build"
  publish = "local_lift_digital/.next"

[secrets_scanning]
  omit_keys = [
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_APP_ID",
    "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
  ]